# Generated by Django 5.2.3 on 2025-06-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Summary', models.TextField()),
                ('Degree', models.TextField()),
                ('InstituteName', models.CharField(max_length=50)),
                ('YearofGraduation', models.DateField()),
                ('CompanyName', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('YearsofExperience', models.CharField(max_length=100)),
                ('Skills', models.TextField()),
                ('Hobbies', models.TextField()),
                ('Achievements', models.TextField()),
            ],
        ),
    ]
