# Generated by Django 5.2.3 on 2025-06-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='ProfilePicture',
            field=models.ImageField(upload_to='Media/img'),
        ),
    ]
